export const content = {
  en: {
    // App & Branding
    appName: "KG Poultry Farms",
    appSubtitle: "Broiler Farm Operations & Intelligence",
    navigationMenu: "Navigation Menu",
    farmManagement: "Farm Management",

    // Navigation Menu Items
    dashboard: "Dashboard",
    adminDashboard: "Admin Dashboard",
    farmerPortal: "Farmer Portal",
    dailyFarmRecords: "Daily Farm Records",
    feedManagement: "Feed Management",
    medicineAndVaccines: "Medicine & Vaccines",
    dispatchAndBoxSets: "Dispatch & Box Sets",
    reportsAndAnalytics: "Reports & Analytics",
    userManagement: "User Management",
    auditLogs: "Audit Logs",
    batchManagement: "Batch Management",
    batchHistory: "Batch History",
    companyTargets: "Company Targets",

    // Buttons & Actions
    logout: "Logout",
    cancel: "Cancel",
    confirm: "Confirm",
    save: "Save",
    edit: "Edit",
    delete: "Delete",
    view: "View",
    next: "Next",
    previous: "Previous",
    submit: "Submit",
    filter: "Filter",
    all: "All",
    search: "Search",
    newBatch: "New Batch",
    createNewBatch: "Create New Batch",
    setActive: "Set Active",
    completeBatch: "Complete Batch",
    reopenBatch: "Reopen Batch",
    allStatuses: "All Statuses",
    draftOnly: "Draft Only",
    activeOnly: "Active Only",
    completedOnly: "Completed Only",
    searchBatchPlaceholder: "Search by batch number (KG001), name, or farmer...",
    arrivalDate: "ARRIVAL DATE",
    chicksInitRem: "CHICKS (INIT / REM)",
    vehicleDriver: "VEHICLE / DRIVER",
    allBatches: "All Batches",
    placementDate: "PLACEMENT DATE",
    chickSupplier: "CHICK SUPPLIER",
    initialChicks: "INITIAL CHICKS",
    farmerLabel: "FARMER",
    viewBatchHistoryInvoice: "View Batch History & Invoice",
    backToBatchHistory: "Back to Batch History",
    backToBatches: "Back to Batches",
    downloadReport: "Download Report",
    printDetails: "Print Details",
    manageUsers: "Manage Users",
    logFeedStock: "Log Feed Stock",
    receiveFeed: "Receive Feed",
    returnFeed: "Return Feed",
    recordDailyLog: "Record Daily Log",
    targetStandards: "Target Standards",

    // Card Labels & Headers
    available: "AVAILABLE",
    consumed: "CONSUMED",
    arrived: "ARRIVED",
    returned: "Returned",
    status: "Status",
    date: "Date",
    batchNumber: "Batch #",
    assignedFarmer: "Assigned Farmer",
    actions: "Actions",
    lastEntryDate: "LAST ENTRY DATE",
    lastDailyMortality: "LAST DAILY MORTALITY",
    lastFeedConsumed: "LAST FEED CONSUMED",
    lastAvgWeight: "LAST AVG WEIGHT",
    dailyRecordLogHistory: "Daily Record Log History",
    eatBird: "EAT / BIRD",
    target: "TARGET",
    actual: "ACTUAL",
    diff: "DIFF",
    mortality: "MORTALITY",
    bagsConsumed: "BAGS CONSUMED",
    mostRecentRecordDate: "Most recent record date",
    records: "records",

    // Feed Management
    feedStockAndReturn: "Feed Stock & Return Management",
    preStarterStock: "1. PRE-STARTER STOCK",
    starterStock: "2. STARTER STOCK",
    finisherStock: "3. FINISHER STOCK",
    preStarter: "Pre-Starter",
    starter: "Starter",
    finisher: "Finisher",
    firstDeductionPriority: "First deduction priority (Blue Bag)",
    secondDeductionPriority: "Second deduction priority (Green Bag)",
    thirdDeductionPriority: "Third deduction priority (Orange Bag)",
    feedTransactionLogHistory: "Feed Transaction Log History",
    feedType: "Feed Type",
    quantity: "Quantity",
    bags: "Bags",
    transactionType: "Transaction",

    // Dispatch & Vehicles
    salesDispatch: "Sales Dispatch & Vehicle Management",
    netWeight: "Net Wt",
    birds: "Birds",
    avgWeight: "Avg Wt",
    totalNetWeight: "Total Net Weight",
    birdsDispatched: "Birds Dispatched",
    averageBirdWeight: "Average Bird Weight",
    weighedBoxes: "Weighed Boxes",
    openSetWeighing: "Open Set Weighing",
    backToVehicles: "Back to Vehicles",
    editSetup: "Edit Setup",
    invoice: "Invoice",
    createSet: "Create Set",
    boxSetNumber: "Box Set",
    vehicle: "Vehicle",
    driver: "Driver",
    phone: "Phone",
    emptyWeight: "Empty Weight",
    loadedWeight: "Loaded Weight",
    boxes: "Boxes",
    pending: "Pending",
    loaded: "Loaded",
    sets: "Sets",
    boxSetsHistory: "Box Sets History",
    tareLoadedWt: "Tare / Loaded Wt",
    netChickenWt: "Net Chicken Wt",
    clickButtonBelow: "Click button below",
    enterLoadedWeight: "Enter Loaded Weight",
    avg: "Avg",

    // Daily Entry & Mortalities
    mortalityCount: "Mortality Count",
    feedConsumption: "Feed Consumption",
    averageChickenWeight: "Average Chicken Weight (grams)",
    liveFlock: "Live",
    recordDate: "Record Date",
    viewDetails: "View Details",

    // Medicine & Vaccines
    medicineAndVaccinationLog: "Medicine & Vaccination Log",
    vaccineMode: "Vaccine Mode",
    medicineMode: "Medicine Mode",
    logMedicine: "Log Medicine",

    // Statuses
    active: "Active",
    completed: "Completed",
    inProgress: "In Progress",
    readOnlyMode: "Read-Only Mode",

    // Dashboard Keys
    chicksCount: "Chicks Count",
    liveInitialChicks: "Live / Initial Chicks",
    totalFeedConsumed: "Total Feed Consumed",
    consumedTotalArrivedBags: "Consumed / Total Arrived Bags",
    totalMortality: "Total Mortality",
    cumulativeMortality: "Cumulative mortality count",
    latestAvgWeight: "Latest Avg Weight",
    latestEntry: "Latest entry",
    noDailyRecordsYet: "No daily records yet",
    noActiveBatch: "No Active Batch Assigned",
    contactAdminBatch: "Please contact your Administrator to assign you an active farm batch.",
    activeBatches: "Active Batches",
    inProductionShed: "In production shed",
    totalFarmers: "Total Farmers",
    registeredActiveAccounts: "Registered active accounts",
    totalLiveChicks: "Total Live Chicks",
    acrossActiveBatches: "Across active batches",
    totalDispatchedWeight: "Total Dispatched Weight",
    completedSalesDispatches: "Completed sales dispatches",
    farmBatchesOverview: "Farm Batches Overview",
    viewAll: "View All",
    auditLogFeed: "Audit Log Feed",
    logs: "Logs",

    // Weather & Advisories
    changeLocation: "Change",
    feelsLike: "Feels like",
    humidity: "HUMIDITY",
    wind: "WIND",
    liveAdvisory: "Live Advisory",

    // Language Toggle
    language: "Language",
    english: "English",
    tamil: "தமிழ்"
  },

  ta: {
    // App & Branding
    appName: "KG Poultry Farms",
    appSubtitle: "பண்ணை மேலாண்மை",
    navigationMenu: "மெனு",
    farmManagement: "பண்ணை மேலாண்மை",

    // Navigation Menu Items
    dashboard: "முகப்பு",
    adminDashboard: "நிர்வாகி",
    farmerPortal: "முகப்பு",
    dailyFarmRecords: "தினசரி பதிவு",
    feedManagement: "தீவனம்",
    medicineAndVaccines: "மருந்து & தடுப்பூசி",
    dispatchAndBoxSets: "விற்பனை & அனுப்புதல்",
    reportsAndAnalytics: "அறிக்கைகள்",
    userManagement: "பயனர்கள்",
    auditLogs: "தணிக்கைப் பதிவு",
    batchManagement: "தொகுதிகள்",
    batchHistory: "தொகுதி வரலாறு",
    companyTargets: "இலக்குகள்",

    // Buttons & Actions
    logout: "Logout",
    cancel: "ரத்து",
    confirm: "உறுதி",
    save: "சேமி",
    edit: "திருத்து",
    delete: "நீக்கு",
    view: "பார்",
    next: "அடுத்து",
    previous: "முன்பு",
    submit: "சமர்ப்பி",
    filter: "வடிகட்டு",
    all: "அனைத்தும்",
    search: "தேடு",
    newBatch: "புது தொகுதி",
    createNewBatch: "புதுத் தொகுதி உருவாக்கு",
    setActive: "செயல்படுத்து",
    completeBatch: "முடிவுசெய்",
    reopenBatch: "மீண்டும் திற",
    allStatuses: "அனைத்து நிலைகளும்",
    draftOnly: "வரைவு மட்டும்",
    activeOnly: "செயலில் உள்ளவை",
    completedOnly: "முடிந்தவை மட்டும்",
    searchBatchPlaceholder: "தொகுதி எண் (KG001), பெயர் அல்லது விவசாயி தேடுக...",
    arrivalDate: "வந்த தேதி",
    chicksInitRem: "கோழிகள் (ஆரம்பம் / மீதி)",
    vehicleDriver: "வாகனம் / ஓட்டுநர்",
    allBatches: "அனைத்து தொகுதிகளும்",
    placementDate: "வந்த தேதி",
    chickSupplier: "குஞ்சு வழங்கி",
    initialChicks: "ஆரம்ப குஞ்சுகள்",
    farmerLabel: "விவசாயி",
    viewBatchHistoryInvoice: "வரலாறு & ரசீது பார்க்க",
    backToBatchHistory: "வரலாற்றுக்குத் திரும்பு",
    backToBatches: "தொகுதிகளுக்குத் திரும்பு",
    downloadReport: "அறிக்கையை பதிவிறக்கு",
    printDetails: "அச்சிடு",
    manageUsers: "பயனர்கள்",
    logFeedStock: "தீவனப் பதிவு",
    receiveFeed: "தீவனம் வரவு",
    returnFeed: "தீவனம் திருப்பு",
    recordDailyLog: "தினசரி பதிவு",
    targetStandards: "இலக்குகள்",

    // Card Labels & Headers
    available: "இருப்பு",
    consumed: "பயன்பாடு",
    arrived: "வரவு",
    returned: "திருப்புதல்",
    status: "நிலை",
    date: "தேதி",
    batchNumber: "தொகுதி #",
    assignedFarmer: "விவசாயி",
    actions: "செயல்கள்",
    lastEntryDate: "கடைசி தேதி",
    lastDailyMortality: "கடைசி இறப்பு",
    lastFeedConsumed: "கடைசி தீவனம்",
    lastAvgWeight: "கடைசி எடை",
    dailyRecordLogHistory: "தினசரி வரலாறு",
    eatBird: "உணவு",
    target: "இலக்கு",
    actual: "தற்போதைய",
    diff: "மாற்றம்",
    mortality: "இறப்பு",
    bagsConsumed: "பயன்பட்ட பைகள்",
    mostRecentRecordDate: "சமீபத்திய தேதி",
    records: "பதிவுகள்",

    // Feed Management
    feedStockAndReturn: "தீவன மேலாண்மை",
    preStarterStock: "1. ப்ரீ-ஸ்டார்ட்டர்",
    starterStock: "2. ஸ்டார்ட்டர்",
    finisherStock: "3. பினிஷர்",
    preStarter: "ப்ரீ-ஸ்டார்ட்டர்",
    starter: "ஸ்டார்ட்டர்",
    finisher: "பினிஷர்",
    firstDeductionPriority: "முதல் முன்னுரிமை (நீலம்)",
    secondDeductionPriority: "இரண்டாம் முன்னுரிமை (பச்சை)",
    thirdDeductionPriority: "மூன்றாம் முன்னுரிமை (ஆரஞ்சு)",
    feedTransactionLogHistory: "தீவன வரலாறு",
    feedType: "தீவன வகை",
    quantity: "அளவு",
    bags: "பைகள்",
    transactionType: "பரிவர்த்தனை",

    // Dispatch & Vehicles
    salesDispatch: "விற்பனை & அனுப்புதல்",
    netWeight: "நிகர எடை",
    birds: "கோழிகள்",
    avgWeight: "சராசரி எடை",
    totalNetWeight: "மொத்த எடை",
    birdsDispatched: "அனுப்பிய கோழிகள்",
    averageBirdWeight: "சராசரி எடை",
    weighedBoxes: "எடை பெட்டிகள்",
    openSetWeighing: "எடையிடுதல்",
    backToVehicles: "வாகனங்கள்",
    editSetup: "திருத்து",
    invoice: "ரசீது",
    createSet: "புதுத் தொகுதி",
    boxSetNumber: "பெட்டி தொகுதி",
    vehicle: "வாகனம்",
    driver: "ஓட்டுநர்",
    phone: "போன்",
    emptyWeight: "வெற்று எடை",
    loadedWeight: "நிறைந்த எடை",
    boxes: "பெட்டிகள்",
    pending: "நிலுவை",
    loaded: "நிறைந்தது",
    sets: "செட்",
    boxSetsHistory: "தொகுதி வரலாறு",
    tareLoadedWt: "வெற்று / நிறை",
    netChickenWt: "நிகர எடை",
    clickButtonBelow: "கீழே அழுத்தவும்",
    enterLoadedWeight: "நிறைந்த எடை பதிவு",
    avg: "சராசரி",

    // Daily Entry & Mortalities
    mortalityCount: "இறப்பு",
    feedConsumption: "தீவனம்",
    averageChickenWeight: "சராசரி எடை (கி)",
    liveFlock: "உயிருள்ள",
    recordDate: "தேதி",
    viewDetails: "விவரங்கள்",

    // Medicine & Vaccines
    medicineAndVaccinationLog: "மருந்து & தடுப்பூசி",
    vaccineMode: "தடுப்பூசி",
    medicineMode: "மருந்து",
    logMedicine: "மருந்து பதிவு",

    // Statuses
    active: "செயலில்",
    completed: "முடிந்தது",
    inProgress: "நடப்பில்",
    readOnlyMode: "பார்வை மட்டும்",

    // Dashboard Keys
    chicksCount: "கோழிகள் எண்ணிக்கை",
    liveInitialChicks: "உயிருள்ள / ஆரம்ப கோழிகள்",
    totalFeedConsumed: "மொத்த தீவனம்",
    consumedTotalArrivedBags: "பயன்பாடு / வந்தடைந்த பைகள்",
    totalMortality: "மொத்த இறப்பு",
    cumulativeMortality: "மொத்த இறப்பு எண்ணிக்கை",
    latestAvgWeight: "கடைசி எடை",
    latestEntry: "கடைசி பதிவு",
    noDailyRecordsYet: "தினசரி பதிவுகள் இல்லை",
    noActiveBatch: "செயலில் உள்ள தொகுதி இல்லை",
    contactAdminBatch: "உங்களுக்கு தொகையை ஒதுக்க நிர்வாகியை தொடர்பு கொள்ளவும்.",
    activeBatches: "செயலில் உள்ள தொகுதிகள்",
    inProductionShed: "பண்ணையில் உள்ளவை",
    totalFarmers: "விவசாயிகள் எண்ணிக்கை",
    registeredActiveAccounts: "பதிவு செய்த விவசாயிகள்",
    totalLiveChicks: "மொத்த உயிருள்ள கோழிகள்",
    acrossActiveBatches: "செயலில் உள்ள தொகுதிகளில்",
    totalDispatchedWeight: "மொத்த விற்பனை எடை",
    completedSalesDispatches: "விற்பனை செய்யப்பட்ட எடை",
    farmBatchesOverview: "பண்ணை தொகுதிகள் மேலோட்டம்",
    viewAll: "அனைத்தும்",
    auditLogFeed: "தணிக்கைப் பதிவு",
    logs: "பதிவுகள்",

    // Weather & Advisories
    changeLocation: "மாற்று",
    feelsLike: "உணர்வு",
    humidity: "ஈரப்பதம்",
    wind: "காற்று",
    liveAdvisory: "நேரலை",

    // Language Toggle
    language: "மொழி",
    english: "English",
    tamil: "தமிழ்"
  }
};
